let suggestions = [
    "Cardiologia",
    "Dermatologia",
    "endocrinolgia",
    "endocrinolgia",
    "neurologia",
    "geraitria",
    "Oftalmologia",
    "Oncologia",
    "Ortopedia",
    "Pediatria",
    "Saude da mulher",
    "SUS",
    "Exames",
    "Hospitais proximos a mim",
    "Clinica de Saude",
    "UBS",
    "Hospital",
    "Pronto Atendimento",
    "Consultas medicas",
];